server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.2.200
    port: 5672
    username: dev
    password: dev
    virtual-host: /daily
  cloud:
    stream:
      bindings:
        input: # 订阅通道的名称，可以根据实际情况自定义
          destination: studyExchange # 指定要订阅的 Exchange 名称
          group: atguiguB # 消费者组的名称，用于多个消费者共享消息
          content-type: application/json # 消息的内容类型，这里假设是 JSON 格式
          binder: rabbit # 指定使用 RabbitMQ 作为消息组件
eureka:
  client: # 客户端进行 Eureka 注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是 30 秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了 5 秒的间隔（默认是 90 秒）
    instance-id: receive-8803.com   # 在信息列表时显示主机名称
    prefer-ip-address: true    # 访问的路径变为 IP 地址
