server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:rainbow-lpf/springcloud-config.git
          uri: https://github.com/rainbow-lpf/springcloud-config.git
          search-paths:
            - springcloud-config
          skip-ssl-validation: true    #跳过ssl验证
          username: rainbow-lpf@outlook.com
          password: 958712LPF817492.
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 集群版
