server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.13:8848  # 配置 Nacos 地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
